// AIEnhancedProvenance FHIR Shorthand Implementation
// Created: 2025-04-30

Profile: AIProvenance
Parent: Provenance
Id: AI-Provenance
Title: "AI Provenance"
Description: "An AI Provenance is a record of the use of an AI model in generating or enhancing FHIR resources. It captures the details of the AI model used, the input data given to the AI, and the output generated by the AI."
* target 1..* MS
  * ^comment = "The resources that were generated or enhanced by the AI use."
* obeys ai-target-aiast
* occurred[x] 0..1 MS
* reason ^slicing.discriminator.type = #value
* reason ^slicing.discriminator.path = "$this"
* reason ^slicing.rules = #open
* reason contains AIReason 1..1
* reason[AIReason] = $ObsValue#AIAST // "Artificial Intelligence asserted"
* agent ^slicing.discriminator.type = #profile
* agent ^slicing.discriminator.path = "who.resolve()"
* agent ^slicing.rules = #open
* agent contains 
    AIagent 1..* MS and
    Humanagent 0..* MS
* agent[AIagent].who only Reference(AIDevice) // "The AI model used in generating or enhancing the FHIR resource."
  * ^comment = "The AIDevice resource captures the details of the AI model used."
* agent[AIagent].type 1..1 MS
  * ^comment = "The way the AI was used."
* agent[AIagent].role ^slicing.discriminator.type = #value
* agent[AIagent].role ^slicing.discriminator.path = "$this"
* agent[AIagent].role ^slicing.rules = #open
* agent[AIagent].role contains AIrole 1..1
* agent[AIagent].role[AIrole] = AIdeviceTypeCS#Artificial-Intelligence
  * ^comment = "The agent role is set to Artificial Intelligence to indicate that the agent is an AI model."
* agent[Humanagent].who only Reference(Practitioner or PractitionerRole or RelatedPerson or Patient) // "The human that was involved in the AI use."
  * ^comment = "The human agent captures the details of the human that was involved in the AI use."
* agent[Humanagent].type 1..1 MS
  * ^comment = "The way the human was involved in the AI use."
* entity ^slicing.discriminator.type = #profile
* entity ^slicing.discriminator.path = "what.resolve()"
* entity ^slicing.rules = #open
* entity ^slicing.description = "The entities that were used as input to the AI model, including the model card and input prompt."
* entity and entity.what MS
* entity contains 
    modelCard 0..* MS and
    inputPrompt 0..* MS
* entity[modelCard].what only Reference(AIModelCard) // "The model card describing the AI model used."
  * ^comment = "The AIModelCard resource captures the details of the AI model used, including its capabilities, limitations, and intended use."
* entity[modelCard].what 1..1 MS
* entity[modelCard].role = http://hl7.org/fhir/provenance-entity-role#derivation (exactly)
  * ^comment = "The role of the model card in the provenance, indicating that it describes the AI model used."
* entity[inputPrompt].what only Reference(AIInputPrompt) // "The input data used by the AI model."
  * ^comment = "The AIInputPrompt resource captures the details of the input data provided to the AI model."
* entity[inputPrompt].what 1..1 MS
* entity[inputPrompt].role = http://hl7.org/fhir/provenance-entity-role#derivation (exactly)
  * ^comment = "The role of the input data in the provenance, indicating that it was used as input to the AI model."

Invariant: ai-target-aiast
Description: "Every target resource shall be labeled with the AIAST (Artificial Intelligence asserted) security label."
Severity: #warning
// resolve() only evaluates when the target resource is available (e.g., contained or in the same Bundle)
Expression: "target.all(resolve().empty() or resolve().meta.security.where(system = 'http://terminology.hl7.org/CodeSystem/v3-ObservationValue' and code = 'AIAST').exists())"
